// Mock data for students
export const mockStudents = {
    "1": {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
      rollNumber: "CS2023001",
      department: "Computer Science",
      batch: "2023-2027",
      cgpa: "9.2",
      avatarUrl: "/placeholder.svg?height=40&width=40",
      about:
        "I am a Computer Science student passionate about web development and machine learning. I have worked on several projects using React, Node.js, and Python.",
      skills: ["JavaScript", "React", "Node.js", "Python", "Machine Learning"],
      links: {
        github: "https://github.com/johndoe",
        linkedin: "https://linkedin.com/in/johndoe",
        leetcode: "https://leetcode.com/johndoe",
      },
      documents: [
        {
          id: "doc1",
          type: "10th Certificate",
          name: "10th_certificate.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2022-08-10T09:15:00Z",
        },
        {
          id: "doc2",
          type: "12th Certificate",
          name: "12th_certificate.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2022-08-10T09:20:00Z",
        },
        {
          id: "doc3",
          type: "Semester 1 Marksheet",
          name: "sem1_marksheet.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2023-05-15T10:30:00Z",
        },
      ],
    },
    "2": {
      id: "2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      rollNumber: "CS2023002",
      department: "Computer Science",
      batch: "2023-2027",
      cgpa: "8.7",
      avatarUrl: "/placeholder.svg?height=40&width=40",
      about:
        "I am interested in data science and artificial intelligence. I have completed several online courses on these topics and am looking for opportunities to apply my knowledge.",
      skills: ["Python", "Data Science", "SQL", "Machine Learning", "Statistics"],
      links: {
        github: "https://github.com/janesmith",
        linkedin: "https://linkedin.com/in/janesmith",
      },
      documents: [
        {
          id: "doc4",
          type: "10th Certificate",
          name: "10th_certificate.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2022-07-05T11:20:00Z",
        },
        {
          id: "doc5",
          type: "12th Certificate",
          name: "12th_certificate.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2022-07-05T11:25:00Z",
        },
        {
          id: "doc6",
          type: "Semester 1 Marksheet",
          name: "sem1_marksheet.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2023-05-10T09:45:00Z",
        },
        {
          id: "doc7",
          type: "Semester 2 Marksheet",
          name: "sem2_marksheet.pdf",
          url: "#",
          verified: false,
          uploadedAt: "2023-12-20T14:45:00Z",
        },
      ],
    },
    "3": {
      id: "3",
      name: "Michael Johnson",
      email: "michael.johnson@example.com",
      rollNumber: "EC2023001",
      department: "Electronics",
      batch: "2023-2027",
      cgpa: "8.9",
      avatarUrl: "/placeholder.svg?height=40&width=40",
      about:
        "Electronics enthusiast with a passion for circuit design and embedded systems. I enjoy working on IoT projects and have experience with Arduino and Raspberry Pi.",
      skills: ["C++", "Arduino", "Embedded Systems", "Circuit Design", "IoT"],
      links: {
        github: "https://github.com/michaelj",
        linkedin: "https://linkedin.com/in/michaelj",
      },
      documents: [
        {
          id: "doc8",
          type: "10th Certificate",
          name: "10th_certificate.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2022-06-15T10:20:00Z",
        },
        {
          id: "doc9",
          type: "12th Certificate",
          name: "12th_certificate.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2022-06-15T10:25:00Z",
        },
        {
          id: "doc10",
          type: "Semester 1 Marksheet",
          name: "sem1_marksheet.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2023-05-12T14:30:00Z",
        },
      ],
    },
    "4": {
      id: "4",
      name: "Emily Brown",
      email: "emily.brown@example.com",
      rollNumber: "ME2023001",
      department: "Mechanical",
      batch: "2023-2027",
      cgpa: "8.5",
      avatarUrl: "/placeholder.svg?height=40&width=40",
      about:
        "Mechanical engineering student with an interest in CAD design and robotics. I have participated in several robotics competitions and have experience with SolidWorks and AutoCAD.",
      skills: ["SolidWorks", "AutoCAD", "Robotics", "3D Printing", "MATLAB"],
      links: {
        github: "https://github.com/emilyb",
        linkedin: "https://linkedin.com/in/emilyb",
      },
      documents: [
        {
          id: "doc11",
          type: "10th Certificate",
          name: "10th_certificate.pdf",
          url: "#",
          verified: false,
          uploadedAt: "2022-07-20T09:15:00Z",
        },
        {
          id: "doc12",
          type: "12th Certificate",
          name: "12th_certificate.pdf",
          url: "#",
          verified: false,
          uploadedAt: "2022-07-20T09:20:00Z",
        },
      ],
    },
    "5": {
      id: "5",
      name: "David Wilson",
      email: "david.wilson@example.com",
      rollNumber: "CS2022001",
      department: "Computer Science",
      batch: "2022-2026",
      cgpa: "9.0",
      avatarUrl: "/placeholder.svg?height=40&width=40",
      about:
        "Computer Science student with a focus on cybersecurity and network security. I have completed certifications in ethical hacking and network security.",
      skills: ["Cybersecurity", "Ethical Hacking", "Network Security", "Python", "Linux"],
      links: {
        github: "https://github.com/davidw",
        linkedin: "https://linkedin.com/in/davidw",
        leetcode: "https://leetcode.com/davidw",
      },
      documents: [
        {
          id: "doc13",
          type: "10th Certificate",
          name: "10th_certificate.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2021-07-10T10:15:00Z",
        },
        {
          id: "doc14",
          type: "12th Certificate",
          name: "12th_certificate.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2021-07-10T10:20:00Z",
        },
        {
          id: "doc15",
          type: "Semester 1 Marksheet",
          name: "sem1_marksheet.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2022-05-15T11:30:00Z",
        },
        {
          id: "doc16",
          type: "Semester 2 Marksheet",
          name: "sem2_marksheet.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2022-12-20T14:45:00Z",
        },
        {
          id: "doc17",
          type: "Semester 3 Marksheet",
          name: "sem3_marksheet.pdf",
          url: "#",
          verified: true,
          uploadedAt: "2023-05-18T09:30:00Z",
        },
      ],
    },
  }
  
  // Mock data for pending verifications
  export const mockPendingDocuments = [
    {
      id: "1",
      studentId: "2",
      studentName: "Jane Smith",
      studentAvatar: "/placeholder.svg?height=40&width=40",
      documentType: "Semester 2 Marksheet",
      documentName: "sem2_marksheet.pdf",
      documentUrl: "#",
      uploadedAt: "2023-12-20T14:45:00Z",
    },
    {
      id: "2",
      studentId: "4",
      studentName: "Emily Brown",
      studentAvatar: "/placeholder.svg?height=40&width=40",
      documentType: "10th Certificate",
      documentName: "10th_certificate.pdf",
      documentUrl: "#",
      uploadedAt: "2023-11-15T10:30:00Z",
    },
    {
      id: "3",
      studentId: "4",
      studentName: "Emily Brown",
      studentAvatar: "/placeholder.svg?height=40&width=40",
      documentType: "12th Certificate",
      documentName: "12th_certificate.pdf",
      documentUrl: "#",
      uploadedAt: "2023-11-15T10:35:00Z",
    },
  ]
  
  // Mock data for pending CGPA verifications
  export const mockPendingCGPA = [
    {
      id: "1",
      studentId: "2",
      studentName: "Jane Smith",
      studentAvatar: "/placeholder.svg?height=40&width=40",
      department: "Computer Science",
      batch: "2023-2027",
      currentCGPA: "8.7",
      lastUpdated: "2023-12-15T14:45:00Z",
    },
    {
      id: "2",
      studentId: "4",
      studentName: "Emily Brown",
      studentAvatar: "/placeholder.svg?height=40&width=40",
      department: "Mechanical",
      batch: "2023-2027",
      currentCGPA: "8.5",
      lastUpdated: "2023-11-10T10:30:00Z",
    },
  ]
  
  // Mock data for blog posts
  export const mockBlogPosts = [
    {
      id: 1,
      title: "My Interview Experience at Google",
      author: "Sarah Johnson",
      authorImage: "/placeholder.svg?height=40&width=40",
      date: "May 15, 2025",
      category: "Interview Experience",
      excerpt:
        "I recently interviewed at Google for a Software Engineer position. Here's my detailed experience and tips for cracking the interview.",
      readTime: "8 min read",
    },
    {
      id: 2,
      title: "How I Prepared for Technical Interviews",
      author: "Rahul Sharma",
      authorImage: "/placeholder.svg?height=40&width=40",
      date: "May 10, 2025",
      category: "Preparation Resources",
      excerpt:
        "A comprehensive guide on how I prepared for technical interviews, including resources, practice strategies, and time management.",
      readTime: "12 min read",
    },
    {
      id: 3,
      title: "Data Structures and Algorithms: A Complete Roadmap",
      author: "Priya Patel",
      authorImage: "/placeholder.svg?height=40&width=40",
      date: "May 5, 2025",
      category: "Preparation Resources",
      excerpt:
        "A step-by-step roadmap to master Data Structures and Algorithms for placement interviews, with recommended resources.",
      readTime: "15 min read",
    },
    {
      id: 4,
      title: "My Amazon Interview Journey",
      author: "Amit Kumar",
      authorImage: "/placeholder.svg?height=40&width=40",
      date: "April 28, 2025",
      category: "Interview Experience",
      excerpt:
        "From application to offer: My complete journey through Amazon's interview process for a Data Scientist role.",
      readTime: "10 min read",
    },
  ]
  
  // Mock data for company visits
  export const mockCompanyVisits = [
    {
      id: 1,
      company: "Google",
      logo: "/placeholder.svg?height=40&width=40",
      date: "June 15, 2025",
      positions: ["Software Engineer", "Product Manager"],
      eligibility: "CGPA ≥ 8.0",
      status: "Upcoming",
    },
    {
      id: 2,
      company: "Microsoft",
      logo: "/placeholder.svg?height=40&width=40",
      date: "June 10, 2025",
      positions: ["Software Engineer", "Data Scientist"],
      eligibility: "CGPA ≥ 7.5",
      status: "Upcoming",
    },
    {
      id: 3,
      company: "Amazon",
      logo: "/placeholder.svg?height=40&width=40",
      date: "May 20, 2025",
      positions: ["SDE", "Business Analyst"],
      eligibility: "CGPA ≥ 7.0",
      status: "Completed",
    },
    {
      id: 4,
      company: "Adobe",
      logo: "/placeholder.svg?height=40&width=40",
      date: "May 5, 2025",
      positions: ["Software Engineer", "UX Designer"],
      eligibility: "CGPA ≥ 7.5",
      status: "Completed",
    },
    {
      id: 5,
      company: "IBM",
      logo: "/placeholder.svg?height=40&width=40",
      date: "April 25, 2025",
      positions: ["Software Developer", "Data Analyst"],
      eligibility: "CGPA ≥ 7.0",
      status: "Completed",
    },
  ]
  
  // Document types for upload
  export const documentTypes = [
    "10th Certificate",
    "12th Certificate",
    "Semester 1 Marksheet",
    "Semester 2 Marksheet",
    "Semester 3 Marksheet",
    "Semester 4 Marksheet",
    "Semester 5 Marksheet",
    "Semester 6 Marksheet",
    "Semester 7 Marksheet",
    "Semester 8 Marksheet",
    "Degree Certificate",
    "Resume",
    "Other",
  ]
  